### ISSUE TITLE
Error when using sf_to_geoda(sf_obj, with_table = TRUE)

### ISSUE THREAD

**Issue by silvia-ventoruzzo** [lixun910/rgeoda#1]
Hello, 

I wanted to create a GEODA object from my sf dataframe and attaching the table to it, but it throws the following error:

Error in f(...) : could not find function "f"
3. f(x, ...)
2. tbl$AddStringColumn(col_names[[i]], dat)
1. sf_to_geoda(sf_obj = data_sf, with_table = TRUE)

Best regards,
Silvia

**Comment by lixun910** [comment]
Thanks @silvia-ventoruzzo !  Do you know which rgeoda version you are using right now? rgeoda is in active development, and the source code has been changed frequently. (sorry for that). If you can let me know which rgeoda version, what OS you are using. I will try to replicate it and fix it.

Using latest rgeoda (devtools::install_github("lixun910/rgeoda")) , you should be able to call sf_to_geoda, e.g.

```R
library(rgeoda)
guerry_path <- system.file("extdata", "Guerry.shp", package = "rgeoda")

library(sf)
guerry_sf <- st_read(guerry_path)

guerry_gda <- sf_to_geoda(guerry_sf)
queen_w <- queen_weights(guerry_gda)

guerry_df <- as.data.frame(guerry_sf)
crm_prs <- guerry_df['Crm_prs'][,1]
```

**Comment by silvia-ventoruzzo** [comment]
Hi @lixun910, thanks for your reply.

I tried your reproducible example. The code works file when I run 
`guerry_gda <- sf_to_geoda(guerry_sf)` 
but I get the error above when I run 
`guerry_gda <- sf_to_geoda(guerry_sf, with_table = TRUE)`

Underneath the result to my `sessionInfo()` call:
> R version 3.6.3 (2020-02-29)
> Platform: x86_64-w64-mingw32/x64 (64-bit)
> Running under: Windows 7 x64 (build 7601) Service Pack 1
> 
> Matrix products: default
> 
> Random number generation:
>  RNG:     L'Ecuyer-CMRG 
>  Normal:  Inversion 
>  Sample:  Rejection 
>  
> locale:
> [1] LC_COLLATE=German_Germany.1252  LC_CTYPE=German_Germany.1252   
> [3] LC_MONETARY=German_Germany.1252 LC_NUMERIC=C                   
> [5] LC_TIME=German_Germany.1252    
> 
> attached base packages:
> [1] stats     graphics  grDevices utils     datasets  methods   base     
> 
> other attached packages:
>  [1] fpc_2.2-5             progress_1.2.2        rgeoda_0.0.4         
>  [4] devtools_2.3.0        usethis_1.6.1         spdep_1.1-3          
>  [7] spData_0.3.5          sp_1.4-2              EnsCat_1.1           
> [10] seqinr_3.6-1          dendextend_1.13.4     ClustGeo_2.0         
> [13] ggpubr_0.3.0          gridExtra_2.3         clValid_0.6-7        
> [16] dynamicTreeCut_1.63-1 factoextra_1.0.7      ggdendro_0.1-20      
> [19] cluster_2.1.0         HiClimR_2.1.6         dtwclust_5.5.6       
> [22] dtw_1.21-3            proxy_0.4-24          fastDummies_1.6.1    
> [25] GGally_1.5.0          lwgeom_0.2-4          sf_0.9-3             
> [28] lubridate_1.7.8       forcats_0.5.0         stringr_1.4.0        
> [31] dplyr_0.8.5           purrr_0.3.4           readr_1.3.1          
> [34] tidyr_1.1.0           tibble_3.0.1          ggplot2_3.3.1        
> [37] tidyverse_1.3.0      
> 
> loaded via a namespace (and not attached):
>   [1] tidyselect_1.1.0    grid_3.6.3          munsell_0.5.0      
>   [4] codetools_0.2-16    units_0.6-6         withr_2.2.0        
>   [7] colorspace_1.4-1    knitr_1.28          rstudioapi_0.11    
>  [10] stats4_3.6.3        robustbase_0.93-6   ggsignif_0.6.0     
>  [13] labeling_0.3        farver_2.0.3        rprojroot_1.3-2    
>  [16] coda_0.19-3         LearnBayes_2.15.1   vctrs_0.3.0        
>  [19] generics_0.0.2      xfun_0.14           diptest_0.75-7     
>  [22] R6_2.4.1            clue_0.3-57         flexmix_2.3-15     
>  [25] reshape_0.8.8       assertthat_0.2.1    promises_1.1.0     
>  [28] scales_1.1.1        nnet_7.3-12         gtable_0.3.0       
>  [31] processx_3.4.2      rlang_0.4.6         splines_3.6.3      
>  [34] rstatix_0.5.0       broom_0.5.6         yaml_2.2.1         
>  [37] reshape2_1.4.4      abind_1.4-5         modelr_0.1.8       
>  [40] backports_1.1.7     httpuv_1.5.3.1      tools_3.6.3        
>  [43] wkb_0.4-0           ellipsis_0.3.1      raster_3.1-5       
>  [46] RColorBrewer_1.1-2  sessioninfo_1.1.1   Rcpp_1.0.4.6       
>  [49] plyr_1.8.6          classInt_0.4-3      ps_1.3.3           
>  [52] prettyunits_1.1.1   deldir_0.1-25       viridis_0.5.1      
>  [55] cowplot_1.0.0       haven_2.3.0         ggrepel_0.8.2      
>  [58] fs_1.4.1            magrittr_1.5        data.table_1.12.8  
>  [61] RSpectra_0.16-0     openxlsx_4.1.5      gmodels_2.18.1     
>  [64] reprex_0.3.0        pkgload_1.0.2       flexclust_1.4-0    
>  [67] hms_0.5.3           shinyjs_1.1         mime_0.9           
>  [70] xtable_1.8-4        rio_0.5.16          mclust_5.4.6       
>  [73] readxl_1.3.1        testthat_2.3.2      compiler_3.6.3     
>  [76] KernSmooth_2.23-16  ncdf4_1.17          crayon_1.3.4       
>  [79] htmltools_0.4.0     later_1.0.0         expm_0.999-4       
>  [82] RcppParallel_5.0.1  DBI_1.1.0           dbplyr_1.4.4       
>  [85] MASS_7.3-51.5       boot_1.3-24         Matrix_1.2-18      
>  [88] ade4_1.7-15         car_3.0-8           cli_2.0.2          
>  [91] gdata_2.18.0        parallel_3.6.3      pkgconfig_2.0.3    
>  [94] bigmemory.sri_0.1.3 foreign_0.8-75      xml2_1.3.2         
>  [97] foreach_1.5.0       rvest_0.3.5         callr_3.4.3        
> [100] digest_0.6.25       cellranger_1.1.0    curl_4.3           
> [103] kernlab_0.9-29      shiny_1.4.0.2       gtools_3.8.2       
> [106] modeltools_0.2-23   nloptr_1.2.2.1      lifecycle_0.2.0    
> [109] nlme_3.1-144        jsonlite_1.6.1      carData_3.0-4      
> [112] bigmemory_4.5.36    desc_1.2.0          viridisLite_0.3.0  
> [115] fansi_0.4.1         pillar_1.4.4        lattice_0.20-38    
> [118] fastmap_1.0.1       httr_1.4.1          DEoptimR_1.0-8     
> [121] pkgbuild_1.0.8      glue_1.4.1          remotes_2.1.1      
> [124] zip_2.0.4           prabclus_2.3-2      iterators_1.0.12   
> [127] class_7.3-15        stringi_1.4.6       blob_1.2.1         
> [130] memoise_1.1.0       e1071_1.7-3

**Comment by silvia-ventoruzzo** [comment]
I tried it also on another machine and got the same error when running `guerry_gda <- sf_to_geoda(guerry_sf, with_table = TRUE)`.

Call to `sessionInfo()`:
> R version 3.6.3 (2020-02-29)
> Platform: x86_64-apple-darwin15.6.0 (64-bit)
> Running under: macOS Catalina 10.15.4
> 
> Matrix products: default
> BLAS:   /System/Library/Frameworks/Accelerate.framework/Versions/A/Frameworks/vecLib.framework/Versions/A/libBLAS.dylib
> LAPACK: /Library/Frameworks/R.framework/Versions/3.6/Resources/lib/libRlapack.dylib
> 
> locale:
> [1] en_US.UTF-8/en_US.UTF-8/en_US.UTF-8/C/en_US.UTF-8/en_US.UTF-8
> 
> attached base packages:
> [1] stats     graphics  grDevices utils     datasets  methods   base     
> 
> other attached packages:
>  [1] sf_0.9-1        rgeoda_0.0.4    lubridate_1.7.8 RCurl_1.98-1.2  devtools_2.3.0  usethis_1.6.1   forcats_0.5.0  
>  [8] stringr_1.4.0   dplyr_0.8.5     purrr_0.3.3     readr_1.3.1     tidyr_1.0.2     tibble_3.0.0    ggplot2_3.3.0  
> [15] tidyverse_1.3.0
> 
> loaded via a namespace (and not attached):
>  [1] httr_1.4.1         pkgload_1.0.2      jsonlite_1.6.1     modelr_0.1.6       assertthat_0.2.1   sp_1.4-2          
>  [7] cellranger_1.1.0   yaml_2.2.1         remotes_2.1.1      sessioninfo_1.1.1  pillar_1.4.3       backports_1.1.6   
> [13] lattice_0.20-41    glue_1.4.0         digest_0.6.25      rvest_0.3.5        colorspace_1.4-1   pkgconfig_2.0.3   
> [19] broom_0.5.5        haven_2.2.0        scales_1.1.0       processx_3.4.2     wkb_0.4-0          generics_0.0.2    
> [25] ellipsis_0.3.0     withr_2.1.2        cli_2.0.2          magrittr_1.5       crayon_1.3.4       readxl_1.3.1      
> [31] memoise_1.1.0      ps_1.3.2           fs_1.4.1           fansi_0.4.1        nlme_3.1-145       xml2_1.3.1        
> [37] class_7.3-16       pkgbuild_1.0.6     tools_3.6.3        prettyunits_1.1.1  hms_0.5.3          lifecycle_0.2.0   
> [43] munsell_0.5.0      reprex_0.3.0       callr_3.4.3        compiler_3.6.3     e1071_1.7-3        rlang_0.4.5       
> [49] classInt_0.4-3     units_0.6-6        grid_3.6.3         rstudioapi_0.11    bitops_1.0-6       testthat_2.3.2    
> [55] gtable_0.3.0       DBI_1.1.0          curl_4.3           R6_2.4.1           rprojroot_1.3-2    KernSmooth_2.23-16
> [61] desc_1.2.0         stringi_1.4.6      Rcpp_1.0.4.6       vctrs_0.2.4        dbplyr_1.4.2       tidyselect_1.0.0

**Comment by qinyun-lin** [comment]
I got the same error. Once you change it into: "with_table = FALSE", it runs successfully. So the problem is probably with the argument of "with_table = TRUE". @lixun910
